## 0. EDA

In [94]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
mpg_data = sns.load_dataset("mpg")

In [95]:
mpg_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [96]:
mpg_data.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.491160   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   93.500000  2803.500000   
75%     29.000000    8.000000    262.000000  126.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model_year  
count    398.000000  398.000000  
mean      15.568090   76.010050  
std        2.757689    3.697627  
min        8.000000   70.000000  
25%       13.825000   73.000000  
50%       15.500000   76.000000  
75%       17.175000   79.000000  
max       24.800000   82.000000

In [97]:
mpg_data.fillna(0, inplace=True)

In [98]:
X, y = mpg_data.drop(["mpg", "origin", "name"], axis="columns"), mpg_data["mpg"]

X

cylinders  displacement  horsepower  weight  acceleration  model_year
0            8         307.0       130.0    3504          12.0          70
1            8         350.0       165.0    3693          11.5          70
2            8         318.0       150.0    3436          11.0          70
3            8         304.0       150.0    3433          12.0          70
4            8         302.0       140.0    3449          10.5          70
..         ...           ...         ...     ...           ...         ...
393          4         140.0        86.0    2790          15.6          82
394          4          97.0        52.0    2130          24.6          82
395          4         135.0        84.0    2295          11.6          82
396          4         120.0        79.0    2625          18.6          82
397          4         119.0        82.0    2720          19.4          82

[398 rows x 6 columns]

In [99]:
y.head(10)

0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
5    15.0
6    14.0
7    14.0
8    14.0
9    15.0
Name: mpg, dtype: float64

In [100]:
mpg_data.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  398.000000   398.000000   
mean    23.514573    5.454774    193.425879  102.894472  2970.424623   
std      7.815984    1.701004    104.269838   40.269544   846.841774   
min      9.000000    3.000000     68.000000    0.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   92.000000  2803.500000   
75%     29.000000    8.000000    262.000000  125.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model_year  
count    398.000000  398.000000  
mean      15.568090   76.010050  
std        2.757689    3.697627  
min        8.000000   70.000000  
25%       13.825000   73.000000  
50%       15.500000   76.000000  
75%       17.175000   79.000000  
max       24.800000   82.000000

## 1. Train|test split

In [101]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# check that it adds up to 200
print(f"{X_train.shape = }")
print(f"{y_train.shape = }")
print(f"{X_test.shape = }")
print(f"{y_test.shape = }")

X_train.shape = (318, 6)
y_train.shape = (318,)
X_test.shape = (80, 6)
y_test.shape = (80,)


In [102]:
X_test.head(10)

cylinders  displacement  horsepower  weight  acceleration  model_year
198          4          91.0        53.0    1795          17.4          76
396          4         120.0        79.0    2625          18.6          82
33           6         232.0       100.0    2634          13.0          71
208          8         318.0       150.0    3940          13.2          76
93           8         318.0       150.0    4237          14.5          73
84           4          97.0        88.0    2100          16.5          72
373          4         140.0        92.0    2865          16.4          82
94           8         440.0       215.0    4735          11.0          73
222          8         260.0       110.0    4060          19.0          77
126          6         200.0         0.0    2875          17.0          74

In [103]:
X_train.head(10)

cylinders  displacement  horsepower  weight  acceleration  model_year
3            8         304.0       150.0    3433          12.0          70
18           4          97.0        88.0    2130          14.5          70
376          4          91.0        68.0    2025          18.2          82
248          4          91.0        60.0    1800          16.4          78
177          4         115.0        95.0    2694          15.0          75
63           8         400.0       175.0    4385          12.0          72
246          4          78.0        52.0    1985          19.4          78
352          4          98.0        65.0    2380          20.7          81
108          4          97.0        88.0    2279          19.0          73
90           8         429.0       198.0    4952          11.5          73

## 2. Function for evaluation

In [104]:
from sklearn.preprocessing import MinMaxScaler

# instantiate a scaler instance from the class MinMaxScaler
scaler = MinMaxScaler()
# finds min and max from X_train and stores them
scaler.fit(X_train)
scaler

MinMaxScaler()

In [105]:
# uses the min and max from X_train to transform X_train -> scale X_train
scaled_X_train = scaler.transform(X_train)
# transform X_train -> scale X_test
scaled_X_test = scaler.transform(X_test)

# same shape as before
print(f"{scaled_X_train.shape = }")
print(f"{scaled_X_train.min() = }")
print(f"{scaled_X_train.max() = }")

scaled_X_train.shape = (318, 6)
scaled_X_train.min() = 0.0
scaled_X_train.max() = 1.0


In [106]:
print(f"{scaled_X_test.shape = }")
print(f"{scaled_X_test.min() = }")
print(f"{scaled_X_test.max() = }")

scaled_X_test.shape = (80, 6)
scaled_X_test.min() = 0.0
scaled_X_test.max() = 1.0222222222222221


In [107]:
from sklearn.linear_model import LinearRegression

# instantiates a model instance from LinearRegression class
model = LinearRegression()

# trains the model based on scaled_X_train. It finds parameters that defines a plane
# that minimizes the total error between the points and the plane
model.fit(scaled_X_train, y_train)

# här skär den genom y-axeln
print(f"{model.intercept_ = }")

# (w_1 =Tv, w_2 =Radio, w_3 =Tidning)
print(f"{model.coef_ = }")

model.intercept_ = 27.079084724138088
model.coef_ = array([  0.32300772,   0.66888809,   0.45796264, -24.77684007,
         1.29287289,   9.61160273])


In [108]:
scaled_X_test[0]

array([0.2       , 0.05943152, 0.23555556, 0.05160193, 0.55952381,
       0.5       ])

In [109]:
test_sample_features = scaled_X_test[0]
test_sample_label = y_test.values[0]

print(f"{test_sample_features = }")
print(f"{test_sample_label = }")

model.predict(test_sample_features.reshape(1,-1))

test_sample_features = array([0.2       , 0.05943152, 0.23555556, 0.05160193, 0.55952381,
       0.5       ])
test_sample_label = 33.0


array([31.54197676])

In [110]:
y_pred = model.predict(scaled_X_test)
y_pred

array([31.54197676, 30.71249853, 21.77320721, 16.9985214 , 12.60926766,
       26.20786109, 28.91824447,  9.18468069, 17.22118629, 22.53208513,
       12.66912478, 34.9973436 , 26.68632494, 14.05378206, 24.79112605,
        5.90598912, 30.87743285, 23.80317317, 15.87369569, 35.16434193,
       23.45311696, 19.6977337 , 29.32708823, 30.3336956 , 15.10351046,
       34.55685829, 25.77856111, 25.7716112 , 22.17590428,  7.9320226 ,
       29.37133463, 34.95350227, 20.01006035, 24.92237329, 33.1110916 ,
       12.24102234, 24.4712938 , 22.18563523, 12.37770123, 26.96538263,
       27.63815861, 27.41091983, 20.29253254,  7.71736733, 23.25990775,
       33.68187533, 26.59814635, 24.46510779, 22.77738162, 27.69999808,
       23.47736991, 32.52687247, 31.30406035, 10.5779237 , 29.03120581,
        9.37442323, 19.45862325, 28.31444387, 24.25624473, 20.75997907,
       16.48155999, 30.74870554, 24.92696027, 20.30155737, 21.64034448,
       24.35721657, 25.8817386 , 33.73476034, 29.33782986, 12.68

In [111]:
# Här kan vi jämföra ovan predictions mot test datan
y_test.to_numpy()

array([33. , 28. , 19. , 13. , 14. , 27. , 24. , 13. , 17. , 21. , 15. ,
       38. , 26. , 15. , 25. , 12. , 31. , 17. , 16. , 31. , 22. , 22. ,
       22. , 33.5, 18. , 44. , 26. , 24.5, 18.1, 12. , 27. , 36. , 23. ,
       24. , 37.2, 16. , 21. , 19.2, 16. , 29. , 26.8, 27. , 18. , 10. ,
       23. , 36. , 26. , 25. , 25. , 25. , 22. , 34.1, 32.4, 13. , 23.5,
       14. , 18.5, 29.8, 28. , 19. , 11. , 33. , 23. , 21. , 23. , 25. ,
       23.8, 34.4, 24.5, 13. , 34.7, 14. , 15. , 18. , 25. , 19.9, 17.5,
       28. , 29. , 17. ])

In [112]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

# MAE
mean_absolute_error(y_test, y_pred)

2.465533614643654

In [113]:
# MSE
mean_squared_error(y_test, y_pred)

9.43543515961014

In [114]:
# RMSE
np.sqrt(mean_squared_error(y_test, y_pred))

3.071715344821219

In [115]:
X_train

cylinders  displacement  horsepower  weight  acceleration  model_year
3            8         304.0       150.0    3433          12.0          70
18           4          97.0        88.0    2130          14.5          70
376          4          91.0        68.0    2025          18.2          82
248          4          91.0        60.0    1800          16.4          78
177          4         115.0        95.0    2694          15.0          75
..         ...           ...         ...     ...           ...         ...
71           3          70.0        97.0    2330          13.5          72
106          8         350.0       180.0    4499          12.5          73
270          4         134.0        95.0    2515          14.8          78
348          4          89.0        62.0    2050          17.3          81
102          4          97.0        46.0    1950          21.0          73

[318 rows x 6 columns]

## Quicker version with function to get MAE MSE RMSE

OLS står för "Ordinary Least Squares" och är en metod för att lösa linjära regressionsproblem genom att minimera skillnaden mellan de observerade och de förutsägda värdena. Normala ekvationen är en matematisk ekvation som används för att hitta de bästa parametrarna för linjär regression genom att lösa en system av linjära ekvationer.

SVD står för "Singular Value Decomposition" och är en metod för att faktorisera en matris i tre separata matriser: U, Σ och V^T. I linjär regression används SVD för att beräkna parametrarna i normala ekvationen när datamängden är stor eller när matrisen är illa konditionerad. SVD hjälper till att hantera singularitetsproblem och gör beräkningarna mer stabil.

In [116]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# import numpy as np

def evaluate_regression_model(X_train, X_test, y_train, y_test, model):
    # Train the model
    model.fit(X_train, y_train)
    
    # Make predictions
    y_pred = model.predict(X_test)
    
    # Calculate metrics
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    
    return mae, mse, rmse


In [117]:
# from sklearn.linear_model import LinearRegression

# Create a Linear Regression model
linear_regression_model = LinearRegression()

# Call the function to evaluate the model
mae, mse, rmse = evaluate_regression_model(X_train, X_test, y_train, y_test, linear_regression_model)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)


Mean Absolute Error: 2.465533614643653
Mean Squared Error: 9.43543515961012
Root Mean Squared Error: 3.0717153448212158


## 3.

- Import necessary libraries.
- Load the dataset and split it into training and testing sets.
- Define functions for training, predicting, and computing evaluation metrics (MAE, MSE, RMSE).
- Create the specified models.
- Train each model on the training data and evaluate its performance on the testing data.
- Store the evaluation metrics in a DataFrame along with the model names.
- Determine which model performed the best based on the evaluation metrics.

In [118]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures

# Load dataset
mpg_data = sns.load_dataset("mpg")

# Split dataset into features (X) and target variable (y)
X = mpg_data.drop(["mpg", "origin", "name"], axis=1)
y = mpg_data["mpg"]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define function to compute evaluation metrics
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    return mae, mse, rmse

# Create models
models = {
    "Linear Regression (SVD)": LinearRegression(),
    "Linear Regression (SVD) with scaled data": make_pipeline(StandardScaler(), LinearRegression()),
    "Stochastic Gradient Descent with scaled data": make_pipeline(StandardScaler(), SGDRegressor()),
    "Polynomial Linear Regression (Degree 1)": make_pipeline(StandardScaler(), PolynomialFeatures(degree=1), LinearRegression()),
    "Polynomial Linear Regression (Degree 2)": make_pipeline(StandardScaler(), PolynomialFeatures(degree=2), LinearRegression()),
    "Polynomial Linear Regression (Degree 3)": make_pipeline(StandardScaler(), PolynomialFeatures(degree=3), LinearRegression())
}

# Evaluate models
results = []
for name, model in models.items():
    model.fit(X_train, y_train)
    mae, mse, rmse = evaluate_model(model, X_test, y_test)
    results.append({"Model": name, "MAE": mae, "MSE": mse, "RMSE": rmse})

# Create DataFrame with evaluation metrics
metrics_df = pd.DataFrame(results)

# Display DataFrame
print(metrics_df)

# Find model with best performance based on RMSE
best_model = metrics_df.loc[metrics_df["RMSE"].idxmin()]
print("\nBest Model (Minimum RMSE):\n", best_model)


ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values